version: "3.8"
name: "intract-notifications-dev"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: notifications:1:1

  server:
    build: ./server
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
      - kafka
    volumes:
      - ./server:/app
    restart: on-failure

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
    environment:
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: on-failure

volumes:
  pgdata-dev:
